Update for latest ignition provider
If you attempt to use this module with the latest ignition provider,
you'll run into the following error:

```
Error: Error refreshing state: 1 error occurred:
	* module.bastion-usw2.data.ignition_config.bastion: 1 error occurred:
	* module.bastion-usw2.data.ignition_config.bastion: data.ignition_config.bastion: No valid JSON found, make sure you're using .rendered and not .id: invalid character 'f' after top-level value
```

This is resolved by updating `data.ignition_config.bastion` in the
module to use `.rendered` instead of `.id` for each component data
element.

Jira Ticket: DO-933